# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

<<<<<<< HEAD
# Change the following value to '/PROJECT_NAME' ONLY IF your site type is GitHub Pages Project sites
# and doesn't have a custom domain.
baseurl: ""

=======
>>>>>>> chripy-starter/main
# The language of the webpage › http://www.lingoes.net/en/translator/langcode.htm
# If it has the same name as one of the files in folder `_data/locales`, the layout language will also be changed,
# otherwise, the layout language will use the default value of 'en'.
lang: en

<<<<<<< HEAD
# Additional parameters for datetime localization, optional. › https://github.com/iamkun/dayjs/tree/dev/src/locale
prefer_datetime_locale:

# Change to your timezone › http://www.timezoneconverter.com/cgi-bin/findzone/findzone
timezone: Europe/Berlin
=======
# Change to your timezone › https://kevinnovak.github.io/Time-Zone-Picker
timezone:
>>>>>>> chripy-starter/main

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

<<<<<<< HEAD
title: LucEast # the main title

tagline: Writeups, Tutorials and more. # it will display as the sub-title

description: >- # used by seo meta and the atom feed
  A blog for writeups and tutorials round about Hacking .

# fill in the protocol & hostname for your site, e.g., 'https://username.github.io'
url: "https://luceast.github.io"

github:
  username: LucEast # change to your github username

twitter:
  username: Luc_East # change to your twitter username
=======
title: Chirpy # the main title

tagline: A text-focused Jekyll theme # it will display as the sub-title

description: >- # used by seo meta and the atom feed
  A minimal, responsive and feature-rich Jekyll theme for technical writing.

# Fill in the protocol & hostname for your site.
# e.g. 'https://username.github.io', note that it does not end with a '/'.
url: ""

github:
  username: github_username # change to your github username

twitter:
  username: twitter_username # change to your twitter username
>>>>>>> chripy-starter/main

social:
  # Change to your full name.
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
<<<<<<< HEAD
  name: Lucas Ostmann
  email: lucas@luceast.de # change to your email address
  links:
    # The first element serves as the copyright owner's link
    - https://twitter.com/Luc_East # change to your twitter homepage
    - https://github.com/LucEast # change to your github homepage
    # Uncomment below to add more social links
    # - https://www.facebook.com/username
    - https://www.linkedin.com/in/LucEast
=======
  name: your_full_name
  email: example@domain.com # change to your email address
  links:
    # The first element serves as the copyright owner's link
    - https://twitter.com/username # change to your twitter homepage
    - https://github.com/username # change to your github homepage
    # Uncomment below to add more social links
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username
>>>>>>> chripy-starter/main

google_site_verification: # fill in to your verification string

# ↑ --------------------------
# The end of `jekyll-seo-tag` settings

google_analytics:
  id: # fill in your Google Analytics ID
<<<<<<< HEAD
  # Google Analytics pageviews report settings
  pv:
    proxy_endpoint: # fill in the Google Analytics superProxy endpoint of Google App Engine
    cache_path: # the local PV cache data, friendly to visitors from GFW region
=======

goatcounter:
  id: # fill in your Goatcounter ID
>>>>>>> chripy-starter/main

# Prefer color scheme setting.
#
# Note: Keep empty will follow the system prefer color by default,
# and there will be a toggle to switch the theme between dark and light
# on the bottom left of the sidebar.
#
# Available options:
#
#     light  - Use the light color scheme
#     dark   - Use the dark color scheme
#
<<<<<<< HEAD
theme_mode: # [light|dark]
=======
theme_mode: # [light | dark]
>>>>>>> chripy-starter/main

# The CDN endpoint for images.
# Notice that once it is assigned, the CDN url
# will be added to all image (site avatar & posts' images) paths starting with '/'
#
# e.g. 'https://cdn.com'
img_cdn:

# the avatar on sidebar, support local or CORS resources
<<<<<<< HEAD
avatar: https://de.gravatar.com/userimage/111110631/1242aa525d89e56b0fb7fee536a124f1.png?size=200

# boolean type, the global switch for ToC in posts.
=======
avatar:

# The URL of the site-wide social preview image used in SEO `og:image` meta tag.
# It can be overridden by a customized `page.image` in front matter.
social_preview_image: # string, local or CORS resources

# boolean type, the global switch for TOC in posts.
>>>>>>> chripy-starter/main
toc: true

comments:
  active: # The global switch for posts comments, e.g., 'disqus'.  Keep it empty means disable
  # The active options are as follows:
  disqus:
    shortname: # fill with the Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # utterances settings › https://utteranc.es/
  utterances:
    repo: # <gh-username>/<repo>
    issue_term: # < url | pathname | title | ...>
  # Giscus options › https://giscus.app
  giscus:
    repo: # <gh-username>/<repo>
    repo_id:
    category:
    category_id:
    mapping: # optional, default to 'pathname'
    input_position: # optional, default to 'bottom'
    lang: # optional, default to the value of `site.lang`
<<<<<<< HEAD
=======
    reactions_enabled: # optional, default to the value of `1`
>>>>>>> chripy-starter/main

# Self-hosted static assets, optional › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled: # boolean, keep empty means false
    # specify the Jekyll environment, empty means both
    # only works if `assets.self_host.enabled` is 'true'
<<<<<<< HEAD
    env: # [development|production]

pwa:
  enabled: true # the option for PWA feature

paginate: 10

=======
    env: # [development | production]

pwa:
  enabled: true # the option for PWA feature (installable)
  cache:
    enabled: true # the option for PWA offline cache
    # Paths defined here will be excluded from the PWA cache.
    # Usually its value is the `baseurl` of another website that
    # shares the same domain name as the current website.
    deny_paths:
      # - "/example"  # URLs match `<SITE_URL>/example/*` will not be cached by the PWA

paginate: 10

# The base URL of your site
baseurl: ""

>>>>>>> chripy-starter/main
# ------------ The following options are not recommended to be modified ------------------

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts.
      toc: true # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/
  - scope:
<<<<<<< HEAD
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
=======
>>>>>>> chripy-starter/main
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
<<<<<<< HEAD
  - tools
  - README.md
  - CHANGELOG.md
  - LICENSE
  - gulpfile.js
  - node_modules
=======
  - docs
  - tools
  - README.md
  - LICENSE
  - rollup.config.js
>>>>>>> chripy-starter/main
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
